apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: skynet

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend
        image: docker.io/gopal1409/backend

        ports:
        - containerPort: 8080