apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend

        image: docker.io/gopal1409/frontend:75c509ea2e9a104918c5df063e8cca46fabded5b

        ports:
        - containerPort: 80