apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend

        image: docker.io/gopal1409/frontend:a5ca10960a27e2fb20e6f7433bdb85086b9333e5

        ports:
        - containerPort: 80